Panitik/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lms.urls')),
]

lms/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from . import views




urlpatterns = [
    path("", views.LandingPage, name="landing"),
    path("home", views.HomePage, name="home"),
    path("calendar", views.Calendar, name="calendar"),
    path("courses", views.Courses, name="courses"),
    # path("upload/", views.Upload_Image, name="upload_reciept"),
    path("courseinfo/<str:pk>", views.CourseDetails, name="courseinfo"),
    path("meeting/<str:pk>", views.CourseMeeting, name="meeting"),
    path("materials/<str:pk>", views.CourseMaterials, name="materials"),
    path("activities/<str:pk>", views.CourseActivities, name="activities"),
    path("submitactivities/<str:pk>", views.SubmitActivities, name="submitactivities"),
    path("studentdetails/<str:pk>", views.StudentProfile, name="studentdetails"),
    path("editprofile/<str:pk>", views.EditProfile, name="editprofile"),
    path("announcement/<str:pk>", views.CourseAnnouncement, name="announcement"),
    path("chat/<str:room_name>/", views.Chat, name='chat'),
    path("announcement_all/", views.AnnouncementAll, name="announcement-all"),

    # Faculty
    path("faculty/", views.FacultyDashboard, name="faculty"),
    path("faculty_list_activity/<str:subject_id>/<str:section_id>/", views.FacultyListActivity, name="faculty_list_activity"),
    path("faculty_activity/<str:subject_id>/<str:section_id>/", views.FacultyActivity, name="faculty_activity"),
    path("faculty_list_quiz/<str:subject_id>/<str:section_id>/", views.FacultyQuiz, name="faculty_list_quiz"),
    path("create_quiz/<str:subject_id>/<str:section_id>/", views.CreateQuiz, name="create_quiz"),
    path("Isopen_quiz/<str:quiz_id>/", views.FacultyQuizOpen, name="isopen_quiz"),

    # AUTH
    path("register/", views.Register, name="register"),
    path("login/", views.Login, name="login"),
    path("logout/", views.Logout, name="logout"),

    # Download
    path("download/<str:document_id>", views.download, name="download"),
]

lms/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
import locale
import uuid

from django.core.files.storage import FileSystemStorage
from django.db import models



class CustomUser(AbstractUser):
    is_student = models.BooleanField(default=False, verbose_name='Student')
    

class GradeLevel(models.Model):
    grade_level = models.CharField(max_length=50, null=True, blank=True)
    subjects = models.ManyToManyField('Subject')
    
    def __str__(self):
        return self.grade_level

class Section(models.Model):
    section_name = models.CharField(max_length=50, null=True, blank=True)
    grade_level = models.ForeignKey(GradeLevel, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.section_name } - {self.grade_level}"

class Subject(models.Model):
    subject_name = models.CharField(max_length=50, null=True, blank=True)
    schedule = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    faculty = models.ForeignKey('FacultyDetails', on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return self.subject_name
    
class SubjectMeeting(models.Model):
    START_END = (
        ("1", "6:00AM"),
        ("2", "7:00AM"),
        ("3", "8:00AM"),
        ("4", "9:00AM"),
        ("5", "10:00AM"),
        ("6", "11:00AM"),
        ("7", "12:00PM"),
        ("8", "1:00PM"),
        ("9", "2:00PM"),
        ("10", "3:00PM"),
        ("11", "4:00PM"),
        ("12", "5:00PM"),
    )

    MODE = (
        ("1", "Online"),
        ("2", "Face to Face"),
    )

    PLATFORM = (
        ("1", "Google Meet"),
        ("2", "Zoom"),
        ("3", "Microsoft Teams"),
    )

    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True, blank=True)
    start_schedule = models.CharField(max_length=2, choices=START_END, null=True, blank=True)
    end_schedule = models.CharField(max_length=2, choices=START_END, null=True, blank=True)
    mode = models.CharField(max_length=2, choices=MODE, null=True, blank=True)
    room = models.CharField(max_length=50, null=True, blank=True)
    platform = models.CharField(max_length=2, choices=PLATFORM, null=True, blank=True)
    
    class Meta:  
        verbose_name_plural = 'Subject Meetings'

    def __str__(self):
        return f'{self.subject} - {self.section}'
    
class SubjectMaterials(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=50, null=True, blank=True)
    file_materials = models.FileField(upload_to="uploads/materials", null=True, blank=True)

    
    class Meta:  
        verbose_name_plural = 'Subject Materials'

    def __str__(self):
        return f'{self.title}'

class SubjectActivities(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    deadline = models.DateTimeField(null=True, blank=True)
    file_activities = models.FileField(upload_to="uploads/activities", null=True, blank=True)
    is_open = models.BooleanField(default=True)

    class Meta:  
        verbose_name_plural = 'Subject Activities'
    
    def date(self):
        # locale.setlocale(locale.LC_ALL, 'en-US')
        return self.deadline.strftime("%B %d, %Y %I:%M %p")

    def __str__(self):
        return f'{self.title}'

class SumbitActivities(models.Model):
    student = models.ForeignKey('StudentDetails', on_delete=models.CASCADE, null=True, blank=True)
    activity = models.ForeignKey(SubjectActivities, on_delete=models.CASCADE, null=True, blank=True)
    file_activities = models.FileField(upload_to="uploads/activities", null=True, blank=True)
    text_answer = models.TextField(null=True, blank=True)
    date_submitted = models.DateTimeField(auto_now_add=True)

    class Meta:  
        verbose_name_plural = 'Submit Activities'

    def __str__(self):
        return f'{self.student} - {self.activity}'

    
class SubjectAnnouncement(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:  
        verbose_name_plural = 'Subject Announcements'

    def __str__(self):
        return f'{self.title}'
    
    def date(self):
        # locale.setlocale(locale.LC_ALL, 'en-US')
        return self.date_added.strftime("%B %d, %Y")

# class SubjectAttendace(models.Model):

#     pass

# Student
class StudentDetails(models.Model):
    GENDER = (
        ("M", "Male"),
        ("F", "Female"),
    )

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=50, null=True, blank=True)
    middle_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    bdate = models.DateTimeField(null=True, blank=True)
    placebirth = models.CharField(max_length=50, null=True, blank=True)
    # is_available = models.BooleanField(default=False)
    rndid = models.CharField(
        max_length=100, default=uuid.uuid4, editable=False, null=True, blank=True
    )
    profile_pic = models.ImageField(upload_to="uploads/profile_pics", null=True, blank=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True, blank=True)
    lrn = models.CharField(max_length=50, null=True, blank=True)

    class Meta:  
        verbose_name_plural = 'Student Details'

    def date(self):
        # locale.setlocale(locale.LC_ALL, 'en-US')
        return self.bdate.strftime("%B %d, %Y")
        
    def __str__(self):
        return f'{self.first_name} {self.middle_name} {self.last_name}'


class StudentSubjectCourse(models.Model):
    student = models.ForeignKey(StudentDetails, on_delete=models.CASCADE, null=True, blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:  
        verbose_name_plural = 'Student Subject Course'

    def __str__(self):
        return f'{self.student} - {self.subject}'


class Message(models.Model):
    username = models.CharField(max_length=255)
    room = models.CharField(max_length=255)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("date_added",)

class Announcement(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("date_added",)

    def date(self):
        # locale.setlocale(locale.LC_ALL, 'en-US')
        return self.date_added.strftime("%B %d, %Y")

    def __str__(self):
        return self.title
    
    
# Faculty
class FacultyDetails(models.Model):
    GENDER = (
        ("M", "Male"),
        ("F", "Female"),
    )
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=50, null=True, blank=True)
    middle_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER, null=True, blank=True)
    # subjects = models.ManyToManyField(Subject)
    class Meta:
        verbose_name_plural = 'Faculty Details'
    
    def __str__(self):
        return f'{self.first_name} {self.middle_name} {self.last_name}'

# class Test(models.Model):
#     title = models.CharField(max_length=50, null=True, blank=True)
#     description = models.TextField(null=True, blank=True)
#     date_added = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.title

class QuizQuestion(models.Model):
    question = models.TextField(null=True, blank=True)
    choice1 = models.CharField(max_length=255, null=True, blank=True)
    choice2 = models.CharField(max_length=255, null=True, blank=True)
    choice3 = models.CharField(max_length=255, null=True, blank=True)
    choice4 = models.CharField(max_length=255, null=True, blank=True)
    answer = models.CharField(max_length=255, null=True, blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True)
    topic = models.CharField(max_length=255, null=True, blank=True)
    quiz_id = models.CharField(max_length=255, null=True, blank=True, editable=False)

    class Meta:  
        verbose_name_plural = 'Quiz Questions'

    def __str__(self):
        return self.question
    
class Quiz(models.Model):
    faculty = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True, blank=True)

lms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.forms import ModelForm, ValidationError
from .models import *

class DateInput(forms.DateInput):
    input_type = "date"

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ActivityForm(ModelForm):
    class Meta:
        model = SumbitActivities
        fields = '__all__'

class AnnouncementForm(ModelForm):
    class Meta:
        model = SubjectAnnouncement
        fields = '__all__'

class MaterialForm(ModelForm):
    class Meta:
        model = SubjectMaterials
        fields = '__all__'

class MeetingForm(ModelForm):
    class Meta:
        model = SubjectMeeting
        fields = '__all__'

class ProfileForm(ModelForm):
    class Meta:
        model = StudentDetails
        fields = ["first_name", "middle_name", "last_name", "gender", "address", "email", "profile_pic"]

    widgets = {"bdate": DateInput()}

class FacultyActivityForm(ModelForm):
    class Meta:
        model = SubjectActivities
        fields = '__all__'

class QuizForm(ModelForm):
    class Meta:
        model = QuizQuestion
        fields = '__all__'

lms/templates/lms/student/edit_profile.html
{% extends 'lms/base.html' %} 

{% block title %} 

Panitik - Profile

{% endblock %} 


{% block content %} 

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <strong>Edit Profile</strong>
            </div>
            <div class="card-body card-block">
                <form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
                    {% csrf_token %}
                    <div class="row form-group">
                        <div class="col col-md-3"><label class=" form-control-label">Username</label></div>
                        <div class="col-12 col-md-9">
                            <p class="form-control-static">{{request.user.username | title}}</p>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="email-input" class=" form-control-label">First Name </label></div>
                        <div class="col-12 col-md-9">{{form.first_name}}<small class="help-block form-text">Please enter your First Name</small></div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="email-input" class=" form-control-label">Middle Name</label></div>
                        <div class="col-12 col-md-9">{{form.middle_name}}<small class="help-block form-text">Please enter your Middle Name</small></div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="email-input" class=" form-control-label">Last Name </label></div>
                        <div class="col-12 col-md-9">{{form.last_name}}<small class="help-block form-text">Please enter your Last Name</small></div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="email-input" class=" form-control-label">Email</label></div>
                        <div class="col-12 col-md-9">{{form.email}}<small class="help-block form-text">Please enter your email</small></div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label class=" form-control-label">Gender</label></div>
                        <div class="col col-md-9">
                            {{form.gender}}
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label class=" form-control-label">Address</label></div>
                        <div class="col col-md-9">
                            {{form.address}}
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="file-input" class=" form-control-label">File input</label></div>
                        <div class="col-12 col-md-9">{{form.profile_pic}}</div>
                    </div>
                    <button type="submit" class="btn btn-outline-dark">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset" class="btn btn-outline-secondary">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

lms/templates/lms/student/student_calendar.html
{% extends 'lms/base.html' %} 

{% block title %} 

Panitik - Home 

{% endblock %} 


{% block content %} 

<div class="animated fadeIn">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-body">
                    <!-- <h4 class="box-title">Chandler</h4> -->
                    <div class="calender-cont widget-calender"></div>
                        <div id="calendar"></div>
                    </div>
                </div>
        </div>
</div>
  <div class="modal fade none-border" id="event-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-hidden="true"
          >
            &times;
          </button>
          <h4 class="modal-title"><strong>Add New Event</strong></h4>
        </div>
        <div class="modal-body"></div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-default waves-effect"
            data-dismiss="modal"
          >
            Close
          </button>
          <button
            type="button"
            class="btn btn-success save-event waves-effect waves-light"
          >
            Create event
          </button>
          <button
            type="button"
            class="btn btn-danger delete-event waves-effect waves-light"
            data-dismiss="modal"
          >
            Delete
          </button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

lms/templates/lms/student/student_chat.html
{% extends 'lms/base.html' %} 
{% load static %}

{% block title %} 

Panitik - Chat

{% endblock %} 


{% block content %} 

<div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title box-title">{{room_name}}</h4>
          <div class="card-content">
            <div class="messenger-box">
            
              <ul style="height: 610px; overflow: auto" id="messageBody">
                {% for message in messages %}
                <li>
                  <div class="msg-received msg-container">
                    <div class="msg-sent msg-container"></div>
                    <div class="avatar">
                      <div class="send-time">{{message.date_added|date:'N d h:i A' }}</div>
                    </div>
                    <div class="msg-box" id="message-text">
                      <div class="inner-box">
                        <div class="name"><b>{{message.username}}</b></div>
                        <div class="meg">
                            {{message.content}}
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                {% endfor %}
              </ul>
              <script>
                var messageBody = document.querySelector('#messageBody');
                messageBody.scrollTop = messageBody.scrollHeight - messageBody.clientHeight;
                </script>
              <div class="send-mgs">
                <div class="yourmsg">
                  <input class="form-control" type="text" id="input" />
                </div>
                <button class="btn msg-send-btn" id="submit">
                  <i class="pe-7s-paper-plane"></i>
                </button>
              </div>
            </div>
            <!-- /.messenger-box -->
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
  {{request.user.username|json_script:"user_name"}}
  {{room_name|json_script:"room-name"}}
  <script src="{% static 'js/index.js' %}"></script>

  {% endblock %}

lms/templates/lms/student/student_profile.html
{% extends 'lms/base.html' %} 

{% block title %} 

Panitik - Profile

{% endblock %} 


{% block content %} 

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong>Student Profile</strong>
            </div>
            <div style="text-align: center; padding-top: 1rem;">
                {% if profile.profile_pic %}
                <a href="#">
                    <img class="align-self-center rounded-circle mr-3" style="width:100px; height:100px;" alt=""  
                    src="{{profile.profile_pic.url}}"
                  />
                </a>
                {% else %}
                <a href="#">
                    <img class="align-self-center rounded-circle mr-3" style="width:100px; height:100px;" alt=""  
                    src="https://api.dicebear.com/7.x/pixel-art/svg?seed={{request.user}}&hair=short01,short02,short03,short04,short05"
                  />
                </a>
                {% endif %}
            </div>
            <div class="card-body card-block">
                <form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">LRN</label></div>
                        <div class="col-12 col-md-9">
                            <p class="form-control-static">{{profile.lrn}}</p>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label class=" form-control-label">Username</label></div>
                        <div class="col-12 col-md-9">
                            <p class="form-control-static">{{profile.user.username | title}}</p>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Name</label></div>
                        <div class="col-12 col-md-9">
                            <p class="form-control-static">{{profile.first_name}} {{profile.middle_name}} {{profile.last_name}}</p>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Gender</label></div>
                        <div class="col-12 col-md-9">
                            <p class="form-control-static">{{profile.get_gender_display}}</p>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Email</label></div>
                        <div class="col-12 col-md-9">
                            <p class="form-control-static">{{profile.email}}</p>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Birth Date</label></div>
                        <div class="col-12 col-md-9">
                            <p class="form-control-static">{{profile.date}}</p>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Section</label></div>
                        <div class="col-12 col-md-9">
                            <p class="form-control-static">{{profile.section.section_name}}</p>
                        </div>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'editprofile' request.user.studentdetails.id %}" class="btn btn-outline-dark">
                            <i class="fa fa-edit"></i> Edit Profile
                        </a>
                        <!-- <button type="submit" class="btn btn-outline-dark">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>
                        <button type="reset" class="btn btn-outline-secondary">
                            <i class="fa fa-ban"></i> Reset
                        </button> -->
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

lms/templates/lms/student/subject_activities.html
{% extends 'lms/base.html' %} 

{% block title %} 

Panitik - Courses

{% endblock %} 


{% block content %} 

<div class="animated fadeIn">
    <div class="row" style="padding-bottom: 2rem;">
        <h1>Meeting</h1>
    </div>
    <!-- Widgets  -->
    {% for i in meeting %}
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="stat-widget-five">
              <div class="stat-icon dib flat-color-1">
                <i class="ti-layout-media-center-alt"></i>
              </div>
              <div class="stat-content">
                <div class="text-left dib">
                  <div class="stat-text">
                    <span>{{i.subject.subject_name}} - {{i.subject.faculty}}</span>
                  </div>
                  <div class="stat-heading">{{i.get_start_schedule_display}} - {{i.get_end_schedule_display}}</div>
                  {% if i.mode == '1' %}
                    <div class="stat-heading">{{i.get_mode_display}}</div>
                    <div class="stat-heading">{{i.get_platform_display}} <a href="{{i.room}}">Link Here</a></div>
                    {% else %}
                    <div class="stat-heading">{{i.get_mode_display}}</div>
                    <div class="stat-heading">Room - <b>{{i.room}}</b></div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}


    
    <!-- /Widgets -->
  </div>

{% endblock %}

lms/templates/lms/student/subject_announcement.html
{% extends 'lms/base.html' %} 

{% block title %} 

Panitik - Courses

{% endblock %} 


{% block content %} 

<div class="animated fadeIn">
    <div class="row" style="padding-bottom: 2rem;">
        <h1>Announcement</h1>
    </div>
    <!-- Widgets  -->
    {% for i in announcement %}
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="stat-widget-five">
              <div class="stat-icon dib flat-color-1">
                <i class="ti-bolt"></i>
              </div>
              <div class="stat-content">
                <div class="text-left dib">
                  <div class="stat-text">
                    <span>{{i.title}}</span>
                  </div>
                  <div class="stat-heading">{{i.date}}</div>
                  <div class="stat-heading">
                   <h3>{{i.description}}</h3>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}


    
    <!-- /Widgets -->
  </div>

{% endblock %}

lms/templates/lms/student/subject_materials.html
{% extends 'lms/base.html' %} 

{% block title %} 

Panitik - Materials

{% endblock %} 


{% block content %} 

<div class="animated fadeIn">
    <div class="row" style="padding-bottom: 2rem;">
        <h1>Materials</h1>
    </div>
    <!-- Widgets  -->
    {% for i in materials %}
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="stat-widget-five">
              <div class="stat-icon dib flat-color-1">
                <i class="ti-layout-media-center-alt"></i>
              </div>
              <div class="stat-content">
                <div class="text-left dib">
                  <div class="stat-text">
                    <span>{{i.subject.subject_name}} - {{i.subject.faculty}}</span>
                  </div>
                  <div class="stat-heading">{{i.title}}</div>
                  {% if i.file_materials %}
                  <div class="stat-heading">View Material Here <a href="{{i.file_materials.url}}" target="_blank">Here...</div>
                  <div class="stat-heading">Download the Pdf <a href="{% url 'download' i.id %}">Here...</div>
                  {% else %}
                  <div class="stat-heading">No file uploaded</div>
                  {% endif %}
                  <!-- {% if i.mode == '1' %}
                    <div class="stat-heading">{{i.get_mode_display}}</div>
                    <div class="stat-heading">{{i.get_platform_display}} <a href="{{i.room}}">Link Here</a></div>
                    {% else %}
                    <div class="stat-heading">{{i.get_mode_display}}</div>
                    <div class="stat-heading">Room - <b>{{i.room}}</b></div>
                  {% endif %} -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}


    
    <!-- /Widgets -->
  </div>

{% endblock %}

lms/templates/lms/student/subject_meeting.html
{% extends 'lms/base.html' %} 

{% block title %} 

Panitik - Courses

{% endblock %} 


{% block content %} 

<div class="animated fadeIn">
    <div class="row" style="padding-bottom: 2rem;">
        <h1>Meeting</h1>
    </div>
    <!-- Widgets  -->
    {% for i in meeting %}
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="stat-widget-five">
              <div class="stat-icon dib flat-color-1">
                <i class="ti-layout-media-center-alt"></i>
              </div>
              <div class="stat-content">
                <div class="text-left dib">
                  <div class="stat-text">
                    <span>{{i.subject.subject_name}} - {{i.subject.faculty}}</span>
                  </div>
                  <div class="stat-heading">{{i.get_start_schedule_display}} - {{i.get_end_schedule_display}}</div>
                  {% if i.mode == '1' %}
                    <div class="stat-heading">{{i.get_mode_display}}</div>
                    <div class="stat-heading">{{i.get_platform_display}} <a href="{{i.room}}">Link Here</a></div>
                    {% else %}
                    <div class="stat-heading">{{i.get_mode_display}}</div>
                    <div class="stat-heading">Room - <b>{{i.room}}</b></div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}


    
    <!-- /Widgets -->
  </div>

{% endblock %}